main: xyz.whynospaces.perktransfer.PerkTransfer
name: PerkTransfer
author: Spaces
version: 0.1-SNAPSHOT
depends: [Vault]
commands:
   perktransfer:
      description: Transfer perks between players.
      usage: /perktransfer [perk] [player]
      permission: perktransfer.use
      permission-message: §cYou do not have permission for this command.
      aliases: [ptransfer, ptrade]
   perkreload:
      description: Reloads perks config.
      usage: /perkreload
      permission: perktransfer.reload
      permission-message: §cYou do not have permission for this command.
      aliases: [preload]